// Common titles/prefixes for members
export const memberTitles = [
  { value: "none", label: "None" },
  { value: "Rev", label: "Rev. (Reverend)" },
  { value: "Pastor", label: "Pastor" },
  { value: "Bishop", label: "Bishop" },
  { value: "Apostle", label: "Apostle" },
  { value: "Prophet", label: "Prophet" },
  { value: "Evangelist", label: "Evangelist" },
  { value: "Elder", label: "Elder" },
  { value: "Deacon", label: "Deacon" },
  { value: "Deaconess", label: "Deaconess" },
  { value: "Dr", label: "Dr. (Doctor)" },
  { value: "Prof", label: "Prof. (Professor)" },
  { value: "Eng", label: "Eng. (Engineer)" },
  { value: "Adv", label: "Adv. (Advocate)" },
  { value: "Mr", label: "Mr." },
  { value: "Mrs", label: "Mrs." },
  { value: "Miss", label: "Miss" },
  { value: "Ms", label: "Ms." },
  { value: "Hon", label: "Hon. (Honorable)" },
  { value: "Amb", label: "Amb. (Ambassador)" },
  { value: "Col", label: "Col. (Colonel)" },
  { value: "Capt", label: "Capt. (Captain)" },
  { value: "Maj", label: "Maj. (Major)" },
  { value: "Lt", label: "Lt. (Lieutenant)" },
  { value: "Sgt", label: "Sgt. (Sergeant)" },
];

// Common professions
export const commonProfessions = [
  "Accountant",
  "Architect",
  "Attorney/Lawyer",
  "Banker",
  "Business Owner",
  "Civil Servant",
  "Consultant",
  "Dentist",
  "Doctor/Physician",
  "Engineer",
  "Farmer",
  "Government Official",
  "Healthcare Worker",
  "IT Professional",
  "Journalist",
  "Lecturer/Teacher",
  "Mechanic",
  "Nurse",
  "Pastor/Minister",
  "Pharmacist",
  "Pilot",
  "Police Officer",
  "Real Estate Agent",
  "Salesperson",
  "Social Worker",
  "Student",
  "Teacher",
  "Veterinarian",
  "Other",
];

